{ console: [Getter],
    DTRACE_NET_SERVER_CONNECTION: [Function],
    DTRACE_NET_STREAM_END: [Function],
    DTRACE_HTTP_SERVER_REQUEST: [Function],
    DTRACE_HTTP_SERVER_RESPONSE: [Function],
    DTRACE_HTTP_CLIENT_REQUEST: [Function],
    DTRACE_HTTP_CLIENT_RESPONSE: [Function],
    global: [Circular],
    process: 
     process {
       title: 'node',
       version: 'v9.2.1',
       moduleLoadList: 
        [ 'Binding contextify',
          'Binding natives',
          'Binding config',
          'NativeModule events',
          'Binding async_wrap',
          'Binding icu',
          'NativeModule util',
          'NativeModule internal/errors',
          'Binding buffer',
          'NativeModule internal/encoding',
          'NativeModule internal/util',
          'Binding util',
          'Binding constants',
          'NativeModule internal/util/types',
          'NativeModule buffer',
          'NativeModule internal/buffer',
          'Binding uv',
          'NativeModule internal/util/comparisons',
          'NativeModule internal/process',
          'NativeModule internal/process/warning',
          'NativeModule internal/process/next_tick',
          'NativeModule async_hooks',
          'NativeModule internal/process/promises',
          'NativeModule internal/process/stdio',
          'Binding performance',
          'NativeModule perf_hooks',
          'NativeModule internal/linkedlist',
          'NativeModule internal/inspector_async_hook',
          'Binding inspector',
          'NativeModule timers',
          'Binding timer_wrap',
          'NativeModule assert',
          'NativeModule module',
          'NativeModule internal/module',
          'NativeModule internal/url',
          'NativeModule internal/querystring',
          'NativeModule querystring',
          'Binding url',
          'NativeModule vm',
          'NativeModule fs',
          'NativeModule path',
          'Binding fs',
          'NativeModule stream',
          'NativeModule internal/streams/legacy',
          'NativeModule _stream_readable',
          'NativeModule internal/streams/BufferList',
          'NativeModule internal/streams/destroy',
          'NativeModule _stream_writable',
          'NativeModule _stream_duplex',
          'NativeModule _stream_transform',
          'NativeModule _stream_passthrough',
          'Binding fs_event_wrap',
          'NativeModule internal/fs',
          'NativeModule internal/loader/Loader',
          'NativeModule internal/loader/ModuleWrap',
          'Internal Binding module_wrap',
          'NativeModule internal/loader/ModuleMap',
          'NativeModule internal/loader/ModuleJob',
          'NativeModule internal/safe_globals',
          'NativeModule internal/loader/ModuleRequest',
          'NativeModule url',
          'NativeModule internal/loader/search',
          'NativeModule console',
          'Binding tty_wrap',
          'NativeModule tty',
          'NativeModule net',
          'NativeModule internal/net',
          'Binding cares_wrap',
          'Binding tcp_wrap',
          'Binding pipe_wrap',
          'Binding stream_wrap',
          'NativeModule dns',
          'NativeModule readline',
          'NativeModule string_decoder',
          'NativeModule internal/readline',
          'Binding signal_wrap',
          'NativeModule internal/repl',
          'NativeModule repl',
          'NativeModule domain',
          'NativeModule os',
          'NativeModule internal/os',
          'Binding os' ],
       versions: { http_parser: '2.7.0',
    node: '9.2.1',
    v8: '6.2.414.44-node.11',
    uv: '1.16.1',
    zlib: '1.2.11',
    ares: '1.13.0',
    modules: '59',
    nghttp2: '1.25.0',
    openssl: '1.0.2n',
    icu: '60.1',
    unicode: '10.0',
    cldr: '32.0',
    tz: '2017c' },
       arch: 'x64',
       platform: 'darwin',
       release: 
        { name: 'node',
          sourceUrl: 'https://nodejs.org/download/release/v9.2.1/node-v9.2.1.tar.gz',
          headersUrl: 'https://nodejs.org/download/release/v9.2.1/node-v9.2.1-headers.tar.gz' },
       argv: [ '/usr/local/bin/node' ],
       execArgv: [],
       env: 
        { TMPDIR: '/var/folders/gj/8xj12pxj56l_mnzgykhyd33r0000gn/T/',
          XPC_FLAGS: '0x0',
          Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.8Tbo1E4BzD/Render',
          TERM: 'xterm-256color',
          LANG: 'zh_CN.UTF-8',
          SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.HTyrc24ELX/Listeners',
          SECURITYSESSIONID: '18911',
          XPC_SERVICE_NAME: '0',
          TERM_PROGRAM: 'Apple_Terminal',
          TERM_PROGRAM_VERSION: '400',
          TERM_SESSION_ID: 'E5DF797E-D3BE-4FD7-94A8-2D660C3BF3A2',
          SHELL: '/bin/zsh',
          HOME: '/Users/wangdejun',
          LOGNAME: 'wangdejun',
          USER: 'wangdejun',
          PATH: '/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/wangdejun/anaconda/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/wangdejun/.rvm/gems/ruby-2.0.0-p643/bin:/Users/wangdejun/.rvm/gems/ruby-2.0.0-p643@global/bin:/Users/wangdejun/.rvm/rubies/ruby-2.0.0-p643/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Library/TeX/texbin:/Users/wangdejun/.rvm/bin',
          SHLVL: '1',
          PWD: '/Users/wangdejun',
          OLDPWD: '/Users/wangdejun',
          ZSH: '/Users/wangdejun/.oh-my-zsh',
          PAGER: 'less',
          LESS: '-R',
          LC_CTYPE: 'zh_CN.UTF-8',
          LSCOLORS: 'Gxfxcxdxbxegedabagacad',
          WORKON_HOME: '/Users/wangdejun/.virtualenvs',
          PROJECT_HOME: '/Users/wangdejun/workspace',
          rvm_prefix: '/Users/wangdejun',
          rvm_path: '/Users/wangdejun/.rvm',
          rvm_bin_path: '/Users/wangdejun/.rvm/bin',
          _system_type: 'Darwin',
          _system_name: 'OSX',
          _system_version: '10.13',
          _system_arch: 'x86_64',
          rvm_version: '1.26.11 (latest)',
          _: '/usr/local/bin/node',
          __CF_USER_TEXT_ENCODING: '0x1F5:0x19:0x34' },
       pid: 22793,
       features: 
        { debug: false,
          uv: true,
          ipv6: true,
          tls_npn: true,
          tls_alpn: true,
          tls_sni: true,
          tls_ocsp: true,
          tls: true },
       ppid: 17517,
       _needImmediateCallback: false,
       execPath: '/usr/local/bin/node',
       debugPort: 9229,
       _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
       _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
       _getActiveRequests: [Function: _getActiveRequests],
       _getActiveHandles: [Function: _getActiveHandles],
       reallyExit: [Function: reallyExit],
       abort: [Function: abort],
       chdir: [Function: chdir],
       cwd: [Function: cwd],
       umask: [Function: umask],
       getuid: [Function: getuid],
       geteuid: [Function: geteuid],
       setuid: [Function: setuid],
       seteuid: [Function: seteuid],
       setgid: [Function: setgid],
       setegid: [Function: setegid],
       getgid: [Function: getgid],
       getegid: [Function: getegid],
       getgroups: [Function: getgroups],
       setgroups: [Function: setgroups],
       initgroups: [Function: initgroups],
       _kill: [Function: _kill],
       _debugProcess: [Function: _debugProcess],
       _debugPause: [Function: _debugPause],
       _debugEnd: [Function: _debugEnd],
       hrtime: [Function: hrtime],
       cpuUsage: [Function: cpuUsage],
       dlopen: [Function: dlopen],
       uptime: [Function: uptime],
       memoryUsage: [Function: memoryUsage],
       binding: [Function: binding],
       _linkedBinding: [Function: _linkedBinding],
       _events: 
        { warning: [Function],
          newListener: [Function],
          removeListener: [Function],
          SIGWINCH: [Array] },
       _rawDebug: [Function],
       _eventsCount: 4,
       domain: [Getter/Setter],
       _maxListeners: undefined,
       _fatalException: [Function],
       _exiting: false,
       assert: [Function],
       config: { target_defaults: [Object], variables: [Object] },
       emitWarning: [Function],
       nextTick: [Function: nextTick],
       _tickCallback: [Function: _tickDomainCallback],
       _tickDomainCallback: [Function: _tickDomainCallback],
       stdout: [Getter],
       stderr: [Getter],
       stdin: [Getter],
       openStdin: [Function],
       exit: [Function],
       kill: [Function],
       argv0: 'node' },
    Buffer: 
     { [Function: Buffer]
       poolSize: 8192,
       from: [Function: from],
       alloc: [Function: alloc],
       allocUnsafe: [Function: allocUnsafe],
       allocUnsafeSlow: [Function: allocUnsafeSlow],
       isBuffer: [Function: isBuffer],
       compare: [Function: compare],
       isEncoding: [Function: isEncoding],
       concat: [Function: concat],
       byteLength: [Function: byteLength],
       [Symbol(node.isEncoding)]: [Function: isEncoding] },
    clearImmediate: [Function],
    clearInterval: [Function],
    clearTimeout: [Function],
    setImmediate: { [Function: setImmediate] [Symbol(util.promisify.custom)]: [Function] },
    setInterval: [Function],
    setTimeout: { [Function: setTimeout] [Symbol(util.promisify.custom)]: [Function] },
    module: 
     Module {
       id: '<repl>',
       exports: {},
       parent: undefined,
       filename: null,
       loaded: false,
       children: [],
       paths: 
        [ '/Users/wangdejun/repl/node_modules',
          '/Users/wangdejun/node_modules',
          '/Users/node_modules',
          '/node_modules',
          '/Users/wangdejun/.node_modules',
          '/Users/wangdejun/.node_libraries',
          '/usr/local/lib/node' ] },
    require: 
     { [Function: require]
       resolve: { [Function: resolve] paths: [Function: paths] },
       main: undefined,
       extensions: { '.js': [Function], '.json': [Function], '.node': [Function] },
       cache: {} } }